apiVersion: v1
kind: Service
metadata:
  labels:
    run: goweb
  name: goweb-svc
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32520
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: goweb
  sessionAffinity: None
  type: NodePort
